srcs/backend/requirements.txt
- daphne 최신버전 설치.
- requiremets.txt 에 daphne 추가.
- daphne가 없다고 장고 컨테이너가 자꾸 죽어서 추가했습니다.
- 파일 추가/수정/삭제
- 의존성 추가 등
---
---
=> build: install daphne manually

srcs/backend/srcs/mysite/oauth/views.py
토큰 리프세리 View 수정
COOKIE -> COOKIES
메서드 이름 오타 변경
Oauth파일의 View에서 TokenRefreshView 부분을 수정함
COOKIE -> COOKIES
---
---
=> fix: COOKIE -> COOKIES

srcs/backend/srcs/mysite/config/settings.py, srcs/backend/srcs/mysite/game_records/admin.py, srcs/backend/srcs/mysite/game_records/apps.py, srcs/backend/srcs/mysite/game_records/models.py, srcs/backend/srcs/mysite/game_records/tests.py, srcs/backend/srcs/mysite/game_records/views.py
데이터베이스 게임 데이터 모델 추가
유저의 게임 데이터 저장 모델 추가함
---
---
close #8
=> feat: Game Record DB scheme model

srcs/backend/srcs/mysite/game_records/models.py
=> fix: game record 스키마 변경

srcs/backend/srcs/mysite/config/urls.py, srcs/backend/srcs/mysite/game_records/models.py, srcs/backend/srcs/mysite/game_records/serializers.py, srcs/backend/srcs/mysite/game_records/urls.py, srcs/backend/srcs/mysite/game_records/views.py, srcs/backend/srcs/mysite/users/models.py
- feat/game records api: GET
- `GET /api/games/[username]` 구현.
- 특정 사용자의 게임 기록을 요청할 수 있습니다.
- OneOnOneMatch, TournamentMatch 모델을 형식에 맞게 serialize하는 serializer 구현.
- 각 모델을 양식에 맞게 직렬화.
- MatchHistorySerializer는 엔드포인트로서, 직렬화된 각 객체를 날짜순으로 정렬해서 반환.
- django shell 로 유저 및 게임 더미 데이터 추가 후 브라우저로 테스트.
```
GET /api/games/tajeong/
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
{
"total_match_history": [
{
"match_type": "배틀",
"total_match": 0,
"win": 0,
"lose": 0
},
{
"match_type": "토너먼트",
"total_match": 10,
"win": 0,
"lose": 10
}
],
"match_history": [
{
"date": [
2025,
2,
10
],
"match_type": "토너먼트",
"enemy": {
"player1": "seojilee",
"player2": "junhapar",
"player3": "tajeong",
"player4": "hyeongsh"
},
"result": "lose"
},
{
"date": [
2025,
2,
10
],
"match_type": …
```
=> feat/game records api: GET

srcs/backend/srcs/mysite/users/serializers.py, srcs/backend/srcs/mysite/users/urls.py, srcs/backend/srcs/mysite/users/views.py
- find username by pattern
- query parameter로 주어진 partial_name으로 시작하는 이름을 검색, 반환합니다.
- 해당하는 유저가 없다면 400 반환.
- `/api/users/find?partial_name=[pattern]` 구현
- 파일 추가/수정/삭제
- 의존성 추가 등
- 브라우저로 테스트.
```
GET /api/users/find/?partial_name=hyeong
HTTP 200 OK
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
{
"user_list": [
"hyeongsh"
]
}
GET /api/users/find/?partial_name=yeong
HTTP 400 Bad Request
Allow: GET, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept
{
"error": "User not found"
}
```
---
---
- #30
=> feat: find username by pattern

srcs/backend/srcs/mysite/users/views.py
- 간단하고 명확한 제목을 작성하세요.
- 파일 추가/수정/삭제
- 의존성 추가 등
---
---
=> hotfix: re-map user auth view with api/users/me url

srcs/backend/srcs/mysite/oauth/views.py
- check nickname duplication at 42 oauth login
- 42 oauth 부분에서 먼저 유저를 고유 id로 검색.
- 검색된 유저가 없다면 유저 생성.
- 같은 유저네임이 존재하는지 확인 후 있다면 이름 뒤에 숫자를 붙인다. (주요 변경 내용)
- `PATCH /api/users/me/`로 유저 정보 변경을 지원하기 때문에 기존에 유저네임을 한번 이상 변경한 유저와 나중에 가입한 유저의 유저네임이 겹칠 수 있다.
- 예: tajeong이 가입 후 이름을 seojilee로 변경. 이후 seojilee가 가입. 이름 충돌. -> seojilee는 seojilee1이 된다.
```python
-        user, created = CustomUser.objects.get_or_create(
-            id = api_data['id'],
-            username = api_data['login'],
-            email = api_data['email'],
-        )
+        user = CustomUser.objects.filter(id=api_data['id']).first() # to prevent DoNotExist
+        if not user:
+            user = CustomUser.objects.create(
+                id = api_data['id'],
+                username = …
```
=> fix: check nickname duplication at 42 oauth login

srcs/backend/srcs/mysite/oauth/views.py
- save profile image url to database
- profile image가 로컬에 저장되기는 하는데 그 경로가 데이터베이스에 저장되고 있지 않아서 수정했습니다.
- 파일 추가/수정/삭제
- 의존성 추가 등
---
---
=> hotfix: save profile image url to database

srcs/backend/srcs/mysite/users/views.py
- API `GET api/users/usernames/` 추가.
- 현재 등록된 모든 유저네임만 반환하는 api를 구현했습니다.
- frontend 측에서 요청했습니다.
- 이와 비슷하지만 사용하고 있지 않은 `GET api/users/`는 불필요한 정보가 많다고 유저네임만 반환하는 api 새로 만들어달라는 요청이 있었습니다.
- 파일 추가/수정/삭제
- 의존성 추가 등
- login과 상관없는 요청이라 curl, browser로 테스트했습니다.
---
---
=> feat: GET api/useres/usernames/

srcs/backend/srcs/mysite/follows/urls.py, srcs/backend/srcs/mysite/oauth/urls.py
- unify url style
- 어느 url은 슬래쉬가 붙어있고 그렇지 않은 것도 있어서 전부 마지막에 슬래쉬를 붙이는 방식으로 통일했습니다.
- 통일성.
- 프론트에서도 헷갈린다고 함.
- 파일 추가/수정/삭제
- 의존성 추가 등
- API 호출이 되는지만 확인하면 되기에 브라우저, curl로 테스트했습니다.
---
---
=> refactor: unify url style - attach slash everywhere

srcs/backend/srcs/mysite/game_records/views.py, srcs/backend/srcs/mysite/users/views.py
- check auth before calling views
- 인증 로직을 제거해둔 뷰 클래스에 다시 인증 로직을 추가.
- 로그인 api 외에는 모두 인증이 필요하다.
- 파일 추가/수정/삭제
- 의존성 추가 등
---
---
=> fix: check auth before calling views

docker-compose.yml
백엔드에서 필요한 DOMAIN 환경변수 추가
- 파일 추가/수정/삭제
- 의존성 추가 등
---
---
=> docs: 백엔드에서 허용된 도메인을 위한 환경변수 추가

srcs/backend/srcs/mysite/online_status/consumers.py
온라인 상태 정보 저장하는 웹소켓 수정
- 파일 추가/수정/삭제
- 의존성 추가 등
---
---
=> fix: 유저 상태정보 저장 되도록 변경

srcs/backend/srcs/mysite/oauth/views.py
- keep user data unique
- oauth 앱에서 유저 정보는 초기에 가입할 때 외에는 건드리지 않는다.
- CustomUser모델에서 금지한 username의 사용자가 가입할 때 고유한 username을 만들어준다.
- 여러 번 로그인할 시 계속 프로필 이미지를 불러오는 오류가 있었다.
- 금지된 유저네임의 사용자는 영원히 가입을 못하게 된다.
- if not user 조건문 바깥에 있던 프로필 사진 저장 로직을 조건문 안으로 옮겼다.
- __generate_unique_username에 FORBIDDEN_PATTERN에 대한 조건을 추가했다.
---
---
=> fix: keep user data unique

srcs/backend/srcs/mysite/chat/consumers.py, srcs/backend/srcs/mysite/chat/gamegroup.py, srcs/backend/srcs/mysite/chat/tournamentconsumer.py
matching off라는 안쓰는 함수 삭제
- 파일 추가/수정/삭제
- 의존성 추가 등
---
---
=> fix: matching off 버그 수정

srcs/backend/srcs/mysite/chat/gamegroup.py, srcs/backend/srcs/mysite/chat/tournamentgamegroup.py
- 간단하고 명확한 제목을 작성하세요.
- 파일 추가/수정/삭제
- 의존성 추가 등
---
---
=> fix: 게임 나갈 떄 유저 체크 버그

srcs/backend/srcs/mysite/users/serializers.py
- do not serialize id for CustomUser. is not needed
- CustomUser의 id를 시리얼라이저에서 삭제했습니다.
- 프론트엔드에서 사용하지 않습니다.
- 파일 추가/수정/삭제
- 의존성 추가 등
- 포스트맨으로 테스트. 잘 사라짐.
---
---
=> fix: do not serialize id for CustomUser. is not needed

srcs/backend/srcs/mysite/chat/tournamentgamegroup.py
슬랙 이슈 수정
- 파일 추가/수정/삭제
- 의존성 추가 등
---
---
=> fix: 들여쓰기 실수 수정

docker-compose.yml
- 간단하고 명확한 제목을 작성하세요.
- 파일 추가/수정/삭제
- 의존성 추가 등
---
---
=> fix: 프론트 환경변수 추가

docker-compose.yml
- 간단하고 명확한 제목을 작성하세요.
- 파일 추가/수정/삭제
- 의존성 추가 등
---
---
=> docs: 주석처리 추가
